version: "3.8"

services:
  postgres:
    container_name: postgres_rustahouse
    image: postgres:17.0-alpine3.20
    environment:
      - POSTGRES_USER=rustahouse
      - POSTGRES_PASSWORD=rustahouse
    ports:
      - "5435:5432"